### ISSUE TITLE
Request timed out behind corporate proxy

### ISSUE THREAD

**Issue by caleyg** [Blazemeter/blazemeter-jenkins-plugin#53]
Hi, I'm using the plugin behind a corporate proxy. 

I have env vars HTTPS_PROXY HTTP_PROXY http_proxy and https_proxy set in all the jenkins environments. In addition to that I have the Proxy set in the Manage Jenkins> Manage Plugins > Advanced. -- I can actually test the url here, and it passes.
In addition I'm actually starting the master with following JAVA_OPTS
```   JAVA_OPTS: '"-Djenkins.install.runSetupWizard=false" "-Dhttp.proxyHost=foo"
        "-Dhttp.proxyPort=8080" "-Dhttps.proxyHost=foo"
        "-Dhttps.proxyPort=8080" "-Dhttp.nonProxyHosts=foo"
```
If I try to test the credentials in the global credential store I get request timed out. If I try to preview the pipeline syntax in the dsl generator I get Check Proxy settings. If I try to POST or get to /descriptorByName/hudson.plugins.blazemeter.BlazemeterCredentialsBAImpl/validate  I get timed out there too. 

Is this plugin /really/ using the proxy settings I've set in the Jenkins environment?

**Comment by artem-fedorov** [comment]
Hi @caleyg 
For set up proxy setting on **jenkins server side** (verify credentials, configure jobs, run jobs on master) set up proxy in the Manage Jenkins> Manage Plugins > Advanced. For verify this config you can add logger for class `hudson.plugins.blazemeter.utils.logger.BzmServerLogger` in the Manage Jenkins> System log>Add new log recorder>name>Add Loggers = `hudson.plugins.blazemeter.utils.logger.BzmServerLogger` > Save.
After click `Test BlazeMeter credentials` button in BlazeMeter credentials config in the log you will see the following logs 
```
Using http.proxyHost = 
Using http.proxyPort = 
Using http.proxyUser = 
Using http.proxyPass = 
```
For set up proxy setting on **jenkins slave side** in the Manage Jenkins> Manage Nodes>_Select Node_ > Configure > Launch method > Advanced >JVM Options
set the following JVM Options: 
`-Dhttp.proxyHost=<HOST> -Dhttp.proxyPort=<PORT> -Dhttp.proxyUser=<USER> -Dhttp.proxyPass=<PASSWORD>`
For verify this config start job on slave and in `workspace` folder look at the first few lines in the bzm-log file.  This file also should contains the same lines about using proxy setting

**Comment by caleyg** [comment]
Thanks for the reply!

So I added the logger as suggested 
```
Apr 18, 2018 5:01:05 PM INFO hudson.plugins.blazemeter.utils.logger.BzmServerLogger info
Get User
Apr 18, 2018 5:01:05 PM FINE hudson.plugins.blazemeter.utils.logger.BzmServerLogger
--> GET https://a.blazemeter.com/api/v4/user?app_key=fooo&_clientId=CI_JENKINS&_clientVersion=4.1 http/1.1
Apr 18, 2018 5:01:05 PM FINE hudson.plugins.blazemeter.utils.logger.BzmServerLogger
Accept: application/json
Apr 18, 2018 5:01:05 PM FINE hudson.plugins.blazemeter.utils.logger.BzmServerLogger
Authorization:...BhZDdmOA==
Apr 18, 2018 5:01:05 PM FINE hudson.plugins.blazemeter.utils.logger.BzmServerLogger
--> END GET
Apr 18, 2018 5:01:25 PM FINE hudson.plugins.blazemeter.utils.logger.BzmServerLogger
<-- HTTP FAILED: java.net.SocketTimeoutException: connect timed out
Apr 18, 2018 5:01:25 PM WARNING hudson.plugins.blazemeter.utils.logger.BzmServerLogger warn
Caught ExecutionException 
java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.java:124)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:220)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:146)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:186)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:212)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at com.blazemeter.api.http.RetryInterceptor.intercept(RetryInterceptor.java:39)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)
	at okhttp3.RealCall.execute(RealCall.java:63)
	at com.blazemeter.api.http.RequestTask.call(RequestTask.java:21)
	at com.blazemeter.api.http.RequestTask.call(RequestTask.java:9)
```

the above is the reply... In my Jenkins Environment under System Information I see 

```
http.nonProxyHosts | foo | --
https.proxyHost | foo| --
https.proxyPort | 8080 | --
```
For some reason even though I'm starting up with the `http.proxyHost` and `http.proxyPort` its not listed there.

I see in https://github.com/Blazemeter/blazemeter-jenkins-plugin/blob/master/src/main/java/hudson/plugins/blazemeter/ProxyConfigurator.java that only the SystemProperty `http.proxyHost` and `http.proxyPort` only being used... is there a reason why `https.proxyHost` being used?

**Comment by artem-fedorov** [comment]
@caleyg 
No reason for use `https.proxyHost`, because jenkins plugin inside create HTTP client using just the following System properties:
https://github.com/Blazemeter/blazemeter-api-client/wiki/Proxy-Configuration
Http client create here: https://github.com/Blazemeter/blazemeter-api-client/blob/master/src/main/java/com/blazemeter/api/http/HttpUtils.java#L173 
This class https://github.com/Blazemeter/blazemeter-jenkins-plugin/blob/master/src/main/java/hudson/plugins/blazemeter/ProxyConfigurator.java just put properties from Manage Jenkins> Manage Plugins > Advanced >Proxy to System properties

**Comment by caleyg** [comment]
<img width="1696" alt="screen shot 2018-04-18 at 10 59 18 am" src="https://user-images.githubusercontent.com/4196377/38949670-e95c8128-42f7-11e8-94d2-23e6f2cc1dc4.png">
Thats the thing though is it is set there. I can even test the url there and passes

**Comment by artem-fedorov** [comment]
@caleyg and after setup correct configuration do the plugin work correctly ?

**Comment by caleyg** [comment]
No, it doesn't it isn't using the Proxy, nor is it printing the logger found here: https://github.com/Blazemeter/blazemeter-api-client/blob/8ab19b41710296876b413287eddd8d406332fac8/src/main/java/com/blazemeter/api/http/HttpUtils.java#L175

The plugin manager can reach the internet just fine and see there are various updates to plugins etc

**Comment by artem-fedorov** [comment]
@caleyg  
 - As I know jenkins store this settings in `/var/lib/jenkins/proxy.xml` file. Maybe you can check it for confirm, that jenkins saved your configuration? 
- Which BlazeMeter plugin version do you use? 
- Did you try restart jenkins?

**Comment by caleyg** [comment]
I was missing the proxy.xml thanks!

**Comment by caleyg** [comment]
I guess I spoke to soon. With proxy.xml nothing logs to the logger I added to Jenkins now. Removing it I can get connection timed out.

I'm using Jenkins 2.114 the plugin version is 4.1; the proxy settings are saved via a groovy script ran before the master turns on.

**Comment by artem-fedorov** [comment]
@caleyg  Did you restart jenkins after return proxy.xml?

**Comment by caleyg** [comment]
I think so? Should I be doing a full restart or a safeRestart?

**Comment by artem-fedorov** [comment]
@caleyg  I don't know difference between it. I usual add /restart to URL e.g.:  localhost:8080/restart

**Comment by caleyg** [comment]
So yeah I'm doing something similar to that... here 
```
def instance = Jenkins.getInstance()

String name        = env.JENKINS_INTERNAL_PROXY_HOST.toString()
int port           = env.JENKINS_INTERNAL_PROXY_PORT.toInteger()
String userName    = ""
String password    = ""
println ("Testing to see if Jenkins needs to schedule a restart")
try{
  proxy_xml = new File('/var/jenkins_home/proxy.xml').getText('UTF-8')
  println ("proxy settings were detected on this system, not scheduling a restart")
  RESTART = 'false'
} catch (e) {
  println ("proxy settings were not detected on this system, scheduling a restart")
  RESTART =  'true'
}

pc = new hudson.ProxyConfiguration(name, port, userName, password, env.JENKINS_INTERNAL_NO_PROXY_HOSTS.replace('|','\n'))
instance.proxy = pc
pc.save()
if (RESTART == 'true' ) {
  Jenkins.instance.restart()
}
```
even still Clicking verify credentials just flashes the animation saying its testing, then quickly goes away. And nothing happens in the logs at all. 

I click on pipeline syntax in the UI and look at the blazemeter object, and it says still checkout proxy settings

**Comment by artem-fedorov** [comment]
looks very hard.. I have never use groovy scripts in jenkins
Maybe  it'll be easier setup System.properties from you groovy script without using `hudson.ProxyConfiguration` class?
https://github.com/Blazemeter/blazemeter-api-client/wiki/Proxy-Configuration

**Comment by caleyg** [comment]
okay i'll try setting those properties and report back

**Comment by caleyg** [comment]
I've tried with the following and no dice ```System.setProperty('http.proxyHost', foo.com')
System.setProperty('http.proxyPort', '8080')
System.setProperty('PROXY_HOST', 'foo.com')
System.setProperty('PROXY_PORT, '8080')

System.properties.each { k,v->
    println "$k = $v"
}

PROXY_HOST = foo.com
PROXY_PORT = 8080
http.proxyPort = 8080
http.proxyHost = foo.com
```

**Comment by caleyg** [comment]
```
Running on Jenkins in /var/jenkins_home/workspace/blazemeter-test
[Pipeline] {
[Pipeline] stage
[Pipeline] { (BlazeMeter test)
[Pipeline] blazeMeterTest
[2018-04-18 22:29:37]: Failure with exception: null
java.lang.NullPointerException
	at java.util.Hashtable.put(Hashtable.java:459)
	at java.util.Properties.setProperty(Properties.java:166)
	at java.lang.System.setProperty(System.java:796)
	at hudson.plugins.blazemeter.ProxyConfigurator.updateProxySettings(ProxyConfigurator.java:31)
	at hudson.plugins.blazemeter.BzmBuild.call(BzmBuild.java:77)
	at hudson.plugins.blazemeter.BzmBuild.call(BzmBuild.java:37)
	at hudson.remoting.LocalChannel.call(LocalChannel.java:45)
	at hudson.plugins.blazemeter.PerformanceBuilder.perform(PerformanceBuilder.java:258)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:80)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:67)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:49)
	at hudson.security.ACL.impersonate(ACL.java:290)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1.run(SynchronousNonBlockingStepExecution.java:46)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```
this is me trying to use it in a pipeline. Its saying that `PROXY_USER` is null and is dying... even though it exists in the jvm as a system.property and -Dhttp.proxyUser. Whats more is the proxy I'm behind doesn't require a username or password, so it shouldn't fail on this being null... is there a try/catch that can be added here?
```
	at hudson.plugins.blazemeter.ProxyConfigurator.updateProxySettings(ProxyConfigurator.java:31)
```

**Comment by caleyg** [comment]
turns out that the username and password has to be set in the manage > plugins > advanced screen... mine are set to foo. Why is his a hard requirement?

**Comment by artem-fedorov** [comment]
Fixed in https://github.com/Blazemeter/blazemeter-jenkins-plugin/pull/54 
You can clone this code and build it on your machine using: `mvn clean package`

**Comment by artem-fedorov** [comment]
@caleyg Can you close this issue if all is ok, please?

**Comment by caleyg** [comment]
Yes, sorry Ill revisit this next week in our new sprint. Thank you
